const ROUTE_BASIC = 'ROUTE_BASIC';
const ROUTE_ADVANCED = 'ROUTE_ADVANCED';
const ROUTE_REAL_WORLD_EXAMPLE = 'ROUTE_REAL_WORLD_EXAMPLE';

const NAVIGATE_BOTTOM_ICON_SIZE = 20;

export default {
  ROUTE_BASIC,
  ROUTE_ADVANCED,
  ROUTE_REAL_WORLD_EXAMPLE,
  NAVIGATE_BOTTOM_ICON_SIZE,
};
